# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: 'some_name'
  username: 'postgres'
  password: 'postgres'
  host: localhost
  port: 5432

test:
  <<: *default
  database: 'some_name2'
  username: 'postgres'
  password: 'postgres'
  host: localhost
  port: 5432

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  database: 'sample_postgres_tests'
  pool: 5
  username: sample_postgres
  password:
